version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - ystrokon-test-context


jobs:
  build:
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      # - run: 
      #     name: Install dependencies
      #     command: npm install --production=false
      # - run: npx wrangler --version
      - run: set
