version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run: wrangler --version
